### ISSUE TITLE
IPv6 AAAA record support

### ISSUE THREAD

**Issue by Azylog** [oz123/coredns-netbox-plugin#11]
Hello,
By reading your code, I can see you've prepared the support of IPv6 records.
If it can helps, Netbox's API can be used with '&family=4' or '&family=6' to filter addresses family.
So you don't have to filter by yourself.

But the localCache still lacks support of different record type, that's another thing.

Thanks for this code, we'll now be able to manage internal DNS zones directly from Netbox (as in 'source of truth').

**Comment by oz123** [comment]
I am glad to hear that my weekend project has been useful for you.
Unfortunately, I currently lack the time to continue to work on this.
This might change in January 2021. For quicker service, consider hiring me directly.

**Comment by oz123** [comment]
You might be happy to hear, this is already WIP. https://github.com/oz123/coredns-netbox-plugin/commit/0e50c4eb8996aa664ae904913dbcf2249582484f

**Comment by oz123** [comment]
Fixed in 6e34de1bfa6fce42923391e08d7c74594a7346bb
