### ISSUE TITLE
tag release please!

### ISSUE THREAD

**Issue by fcolista** [oz123/coredns-netbox-plugin#12]
Hi, when building this plugin for coredns i got an error due to this commit :  https://github.com/oz123/coredns-netbox-plugin/commit/d43c0e5eb4293a75afb005c44b491a8dba59133a 

coredns pull the latest stable version rather than master.

Can you please tag a stable release?

Or perhaps there's a way to tell CoreDNS to build coredns-netbox-plugin from master branch?

Thanks!

**Comment by oz123** [comment]
I believe you can use redirects in your `go.mod` to build what ever tag you want.
If that does not work for you, you'll have to wait a little. I am working on this on my free time.
Unless, this is really urgent, then you can either hire me to work on this directly or sponsor me via https://github.com/sponsors/oz123

**Comment by oz123** [comment]
v0.2 is released.

**Comment by Azylog** [comment]
Hello,
Just wanted to let you know that if we do :
`go get github.com/oz123/coredns-netbox-plugin`
we're getting the v0.1.1

To get v0.2 I had to run : 
`go get github.com/oz123/coredns-netbox-plugin@v0.0.2-0.20211230141133-b5453584aa95`

Which is pretty strange as it seems to be tagged as v0.0.2. Could it be a typo ?

Thanks for this (path for AAAA records incoming in the correct issue)

**Comment by oz123** [comment]
Hmm... I don't know what is going on here. I made both tag and release v0.2 should work. I can test on a different system to see if this is reproducible.
Thanks for the feedback though.

**Comment by oz123** [comment]
OK. My bad! I released 0.2 and go version should be 0.2.0!

Made a new release: `go get -v -u github.com/oz123/coredns-netbox-plugin@v0.2.0` should work now.

**Comment by oz123** [comment]
Alternatively:
```
GONOPROXY=github.com/oz123 go get -v -u github.com/oz123/coredns-netbox-plugin
```

**Comment by Azylog** [comment]
Confirmed : simply using github.com/oz123/coredns-netbox-plugin in plugin.cfg and I got coredns-netbox-plugin@v0.2.0 which seems the correct latest tag.
