### ISSUE TITLE
Instructions on coredns yield error

### ISSUE THREAD

**Issue by echobops** [oz123/coredns-netbox-plugin#24]
The instructions to install this module on the CoreDNS website say: 

![20220211 12_02_55](https://user-images.githubusercontent.com/13371679/153653754-34735634-959e-441b-a99c-ba2980c03d1c.png)

The trailing slash yields an error and halts building while making CoreDNS: 

```
github.com/coredns/coredns imports
        github.com/coredns/coredns/core/plugin imports
        github.com/oz123/coredns-netbox-plugin/: malformed import path "github.com/oz123/coredns-netbox-plugin/": trailing slash
make: *** [Makefile:23: core/plugin/zplugin.go] Error 1
```

**Comment by oz123** [comment]
Thank you for the issue report. I guess this needs to be fixed in coredns documentation.
I am happy you could fix it yourself!
