### ISSUE TITLE
Unable to "parse netbox config" issue? 

### ISSUE THREAD

**Issue by echobops** [oz123/coredns-netbox-plugin#25]
I'm trying to connect coredns with my netbox configuration and am running into this issue: 

```plugin/netbox: Could not parse netbox config```

My Corefile looks like this: 

```
.lan {
        netbox {
          url https://[my.domain]/api/ipam/ip-addresses
          token 7[...]3
        }

        cache 10
        log
        errors
}
```

I tested that API address in Postman w/ the proper credentials and it was able to get information, so I don't think its a permission issue. Anything else I can check?

**Comment by echobops** [comment]
I'm using whatever the coredns plugins page shows: ```netbox:github.com/oz123/coredns-netbox-plugin``` So I'm assuming master?

**Comment by oz123** [comment]
The master branch has many changes, and it contains a working Core file example. Can you check it? 
If that does not work, please pin for version 0.2 .

**Comment by echobops** [comment]
Hmm, I'm not sure what I did, but it started working after I let it sit for a few days. Apparently it pulled version 0.1.1-dev.  Seems like I should probably upgrade it to 0.2?  Since these are pulled on compile of coredns, how do I force a version?

**Comment by echobops** [comment]
Hmm, I pulled 0.2.0 with: 

```go get github.com/oz123/coredns-netbox-plugin@v0.2.0```

Which seemed to have downloaded it, but when running coredns, it still says using 0.1.1-dev.

**Comment by echobops** [comment]
Ah. The 0.2.0 branch still reports version 0.1.1:

```var VERSION = "0.1.1-dev"``` in setup.go.  I think I am using 0.2.0; its just reporting 0.1.1

**Comment by oz123** [comment]
What did you put in your configuration for building? `plugin.cfg`?

**Comment by oz123** [comment]
Just to make it clear, you say you have this in the config:
```
netbox:github.com/oz123/coredns-netbox-plugin
```

That is, using the master branch, where the configuration format is new. If you want to use the older version, you should pin the version:
You can do it by either linking  to a specify tag in you local code, or by modifying `go.mod`:

This is inside the coredns  sources
```
diff --git a/go.mod b/go.mod
index 03cf2f0f2..46435f734 100644
--- a/go.mod
+++ b/go.mod
@@ -23,6 +23,7 @@ require (
        github.com/openzipkin-contrib/zipkin-go-opentracing v0.4.5
        github.com/openzipkin/zipkin-go v0.3.0
        github.com/oschwald/geoip2-golang v1.5.0
+       github.com/oz123/coredns-netbox-plugin v0.1.1
        github.com/philhofer/fwd v1.1.1 // indirect
        github.com/prometheus/client_golang v1.11.0
        github.com/prometheus/client_model v0.2.0
diff --git a/go.sum b/go.sum
index 322163ae7..bd3bb6a0c 100644
```

If you don't pin it, take a look at the documentation for the configuration format.

**Comment by echobops** [comment]
Ah, I see what you're saying. Well, it works now, so I must have pulled 0.2.0 and updated my config which got it to work.

Pulling from master shows that Im' using v0.2.0. 
```
        github.com/oz123/coredns-netbox-plugin v0.2.0
```

Line 28 of setup.go (on master and tagged 0.2.0) is still reporting as _0.1.1-dev_:
https://github.com/oz123/coredns-netbox-plugin/blob/5147544f3d1be73f6165de76deb5fe783fb76b77/setup.go#L28

Thanks!
