### ISSUE TITLE
plugin/netbox: no next plugin found with fallthrough

### ISSUE THREAD

**Issue by Sispheor** [oz123/coredns-netbox-plugin#26]
Hi there 👋. I'm trying to setup this plugin.

The expected behavior is:

- Look into Netbox
- If not found look into the file
- All other requests into the corporate DNS

Current result:

- Dig to a value placed in netbox: **OK**
- Dig to a value placed into the file: **NOK**
- Dig a corporate entry: **OK**

## Config

`Plugin.cfg` order: netbox --> file --> forward

`Corefile`:
```
si.gre.hpecorp.net:53 {
    netbox si.gre.hpecorp.net {
        token secret
        url http://cmsgtest3.gre.hpecorp.net:8000/api/ipam/ip-addresses
        localCacheDuration 300s
        fallthrough 
        timeout 3s
    }
    file /config/db.si.gre.hpecorp.net
    log
    errors
}

.:53 {
    forward . 16.110.135.51 16.110.135.52
    log
    errors
}
```

`db.si.gre.hpecorp.net` file
```
$ORIGIN si.gre.hpecorp.net.
$TTL 1h               ; default expiration time of all resource records without their own TTL value

; =============================== Resource Records ==============================

@	3600 IN	SOA ns1.si.gre.hpecorp.net. admin.si.gre.hpecorp.net. (
				1           ; serial
				7200        ; refresh (2 hours)
				3600        ; retry (1 hour)
				1209600     ; expire (2 weeks)
				3600        ; minimum (1 hour)
				)

	3600 IN NS ns1.si.gre.hpecorp.net.
	3600 IN NS ns2.si.gre.hpecorp.net.

nico IN A 192.168.28.201

```

Log
```
[INFO] Started netbox plugin version 0.1.1-dev
.:53
si.gre.hpecorp.net.:53
CoreDNS-1.9.1
linux/amd64, go1.17.8, 
[INFO] Recored not found in{"count":0,"next":null,"previous":null,"results":[]}
[INFO] 172.17.0.1:44278 - 64076 "A IN nico.si.gre.hpecorp.net. udp 64 false 4096" - - 0 1.570978228s
[ERROR] plugin/errors: 2 nico.si.gre.hpecorp.net. A: plugin/netbox: no next plugin found
```

If I remove the netbox config from the Corefile and keep only the file config I can validate that the "nico" entry is ok.

And BTW it would be nice to read first the file and then ask Netbox. I haven't been able to setup this.

**Comment by andrewheberle** [comment]
Looking at that debug/error output, it seems that you are using an older version of the plugin as the error message `Recored not found` was removed some time ago in the `master` branch.

Also up until PR #19 was merged the `fallthrough` functionality was actually not functional.

> And BTW it would be nice to read first the file and then ask Netbox. I haven't been able to setup this.

I don't believe the `file` plugin supports `fallthrough` so even if you were to change the order of the plugins in `plugin.cfg` and recompile CoreDNS I do not think this is possible...or at least it is not something this plugin can control as far as I understand things.

**Comment by oz123** [comment]
Please see the `examples` directory for working configurations examples with fallthrough and forwarding.

https://github.com/oz123/coredns-netbox-plugin/blob/master/examples/Corefile-with-forwarding
