### ISSUE TITLE
cache metrics not exported

### ISSUE THREAD

**Issue by ahmedoun94** [oz123/coredns-netbox-plugin#29]
I used the official cache plugin but metrics are not exported

**Comment by oz123** [comment]
This should probably be an issue with the cache plugin then?

**Comment by ahmedoun94** [comment]
I developed my own coredns-netbox-plugin (inspired by some of your code). The plugin works well, but I wanted to add the official cache plugin in order to add the cache metrics. But when my plugin is activated, the cache plugin does not send metrics. When I desactivate my netbox-plugin, it does not send the metrics from the cache plugin.

I use the last version of cordens
