### ISSUE TITLE
Return NODATA/NXDOMAIN on queries that don't ask for A records.

### ISSUE THREAD

**Issue by oz123** [oz123/coredns-netbox-plugin#3]
It's ok that only A records are supported, but it's not OK to always answer with A records, even when the query is asking for some other record type. Need to check type and provide NODATA/NXDOMAIN answers as appropriate.

**Comment by andrewheberle** [comment]
I'm unsure if it the best solution but the approach I have taken in PR #22 is to `fallthrough` (if configured) to the next plugin or return SERVFAIL to the client for non A/AAAA records.

**Comment by oz123** [comment]
Well. I like this approach.

**Comment by oz123** [comment]
Once again, thank you so much for your contributions.
