### ISSUE TITLE
Please, release a new version

### ISSUE THREAD

**Issue by Peter2121** [oz123/coredns-netbox-plugin#30]
The commit f7cca1e97d5ff8708cbbab02da6ab3e3f081b048 is really important, it prevents failure of CoreDNS service on Netbox error. Please, release a new version with this commit integrated.

**Comment by Peter2121** [comment]
Ref to https://github.com/oz123/coredns-netbox-plugin/issues/7

**Comment by oz123** [comment]
Done.
