### ISSUE TITLE
PTR record if asked for an IP

### ISSUE THREAD

**Issue by smeinecke** [oz123/coredns-netbox-plugin#34]
Would be cool if the plugin could also do the reverse record and check if the for a requested IP (something like this: 1.178.168.192.in-addr.arpa) a hostname is defined (PTR record / reverse DNS).

**Comment by oz123** [comment]
If the API of netbox can do this, then it can be implemented. But since my time is very limited, I am probably not going to find out very soon.
I would very much accept a PR though.

**Comment by smeinecke** [comment]
Thank you very much. I just checked the API and it should be possible to switch from the "hostname" parameter to "address" - which seems to work fine. I have unfortunately just started with go and therefore don't have enough expertise to implement this quickly yet. However, I will try my hand at it and then open a PR.

**Comment by kotso** [comment]
We are using your plugin @oz123 for a long time to provide ptr resolving based on net box. 

Just refactored code against latest version on plugin and created PR for it.

**Comment by oz123** [comment]
@kotso thanks for your contribution.
