### ISSUE TITLE
Please, add an example of configuration file

### ISSUE THREAD

**Issue by Peter2121** [oz123/coredns-netbox-plugin#5]
...with correct data in the fields.

**Comment by oz123** [comment]
From the README
```
. {
   netbox {
      token <YOU-NETBOX-API-TOKEN>
      url <https://netbox.example.org>
      localCacheDuration <The duration to keep each entry locally before querying netbox again. Use go `time.Duration` notation>
   }
}
```

Replace everything in `<` and `>` with your correct values ...

What have you tried?

**Comment by Peter2121** [comment]
My _working_ config is:
```
domain.local {
   netbox {
      token abcde12345
      url http://10.111.1.130/api/ipam/ip-addresses
      localCacheDuration 10s
   }
}
```

It was not evident _at all_: the format of `localCacheDuration` and the fact that I need to put the full path in url parameter.

**Comment by oz123** [comment]
So this works for you , and you want the example in the readme to be improved?

**Comment by Peter2121** [comment]
Yes, exactly :)
