### ISSUE TITLE
module name incorrect -- plugin won't build

### ISSUE THREAD

**Issue by tjdavis3** [oz123/coredns-netbox-plugin#6]
Attempting to build on a Mac w/ go1.15.  It appears to me that the module name for the plugin should be `github.com/oz123/coredns-netbox-plugin` rather than just coredns-netbox-plugin.  It's causing import errors:

```
TDavis-MACBOOK-6:coredns tdavis$ go generate
TDavis-MACBOOK-6:coredns tdavis$ go build
go: finding module for package github.com/oz123/coredns-netbox-plugin
go: found github.com/oz123/coredns-netbox-plugin in github.com/oz123/coredns-netbox-plugin v0.0.1
go: github.com/coredns/coredns imports
	github.com/coredns/coredns/core/plugin imports
	github.com/oz123/coredns-netbox-plugin: github.com/oz123/coredns-netbox-plugin@v0.0.1: parsing go.mod:
	module declares its path as: coredns-netbox-plugin
	        but was required as: github.com/oz123/coredns-netbox-plugin
```

**Comment by sbilly** [comment]
same issue here

**Comment by tomehb** [comment]
@sbilly @tjdavis3  Did you manage to find a fix for this?

`CGO_ENABLED=0  go build -v -ldflags="-s -w -X github.com/coredns/coredns/coremain.GitCommit=94e027cd-dirty" -o coredns
go: finding module for package github.com/oz123/coredns-netbox-plugin
go: found github.com/oz123/coredns-netbox-plugin in github.com/oz123/coredns-netbox-plugin v0.0.1
go: github.com/coredns/coredns imports
        github.com/coredns/coredns/core/plugin imports
        github.com/oz123/coredns-netbox-plugin: github.com/oz123/coredns-netbox-plugin@v0.0.1: parsing go.mod:
        module declares its path as: coredns-netbox-plugin
                but was required as: github.com/oz123/coredns-netbox-plugin
make: *** [Makefile:16: coredns] Error 1`

**Comment by Peter2121** [comment]
AFAIK, there are fixes in forks
